name: thing
on:
  pull_request: {}
  push:
    branches:
      - main
jobs:
  thing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - one: 'yes'
          two: 'no'
    steps:
     - run: |
         echo ${{ matrix.one }} ${{ matrix.two }}
