name: thing
on:
  pull_request: {}
  push:
    branches:
      - main
jobs:
  prepare:
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
     - id: matrix
       run: |
         echo "matrix=$(jq -rcM -n '.one="yes" | .two = "no" | {"include":[.]}')" >> $GITHUB_OUTPUT
  thing:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
     - run: |
         echo ${{ fromJSON(toJSON(matrix)).one }} ${{ fromJSON(toJSON(matrix)).two }}
